name: mcp_manager

services:
  mcp_manager_db_pgres:
    image: postgres:17.5-bookworm
    env_file:
      - backend/src/mcp_manager_db/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
    - pg_mcp_manager_db:/var/lib/postgresql/data
    - ./backend/src/mcp_manager_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  
  mcp_manager_db_redis:
    image: redis:alpine3.22
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped
    volumes:
      - rds_mcp_manager_db:/data
      - ./backend/src/mcp_manager_db/redis.conf:/usr/local/etc/redis/redis.conf
    


volumes:
  pg_mcp_manager_db:
  rds_mcp_manager_db: