FROM {{ base_image }}


WORKDIR /app

RUN apt-get update && apt-get upgrade -y
RUN pip install --upgrade pip


COPY {{ project_files }} .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE {{ expose_port }}

CMD ["uvicorn", "{{ command }}", "--host", "0.0.0.0", "--port", {{ expose_port }}]