FROM {{ base_image }}


WORKDIR /app

RUN apt-get update && apt-get upgrade -y
RUN pip install --upgrade pip


COPY {{ project_files }} .
COPY requirements_templates/base_requirements.txt .

RUN pip install --no-cache-dir -r base_requirements.txt

{% if requirements %}
RUN pip install --no-cache-dir -r user_requirements.txt
{% endif %}

EXPOSE {{ expose_port }}

CMD ["uvicorn", "mcp:mcp", "--host", "0.0.0.0", "--port", "{{ expose_port }}"]